name: metia
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.24

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.4
  webview_flutter_wkwebview: ^3.18.5
  cached_network_image: ^3.3.1
  app_links: ^6.4.0
  win32_registry: ^1.0.3
  url_launcher: ^6.1.7
  cupertino_icons: ^1.0.8
  pasteboard: ^0.4.0
  image: ^4.1.3
  window_size: ^0.1.0
  html: ^0.15.0
  flutter_slidable: ^4.0.0
  http: ^1.1.0
  marquee: ^2.2.3
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  window_manager: ^0.2.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/Metia.png"




flutter_lints: ^5.0.0


flutter:
        uses-material-design: true
        assets:
          - assets/icons/





